<BuyList>:

    canvas:
        Color:
            rgba: 55/255, 102/255, 76/255, 0.5
        Rectangle:
            size: self.size
            pos: self.pos

    BoxLayout
        id: buylist_layout
        orientation: 'vertical'
        padding: [10,50,10,50]
        spacing: 50


        Label:
            text: "Buy List"
            font_size: 32

        Label:
            text: "Item:"
            halign: 'left'
            font_size: 24
Kaise is here
